from pylab import *

u = loadtxt("u.txt")
v = loadtxt("v.txt")
x = loadtxt("x.txt")
y = loadtxt("y.txt")
w = loadtxt("w.txt")
contourf(x, y, w)
colorbar()
quiver(x, y, u, v)
n, n = shape(x)
xx = linspace(0, 1.0, n)
yy = linspace(0, 1.0, n)
figure()
streamplot(xx, yy, rot90(v,4), rot90(u,4), 4)
figure()
contourf(x, y, u)
colorbar()
figure()
contourf(x, y, v)
colorbar()
show()
